# Snap recipe for the VRRTest utility
# Copyright 2022 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: Zlib
name: vrrtest
title: VRRTest (UNOFFICIAL)
summary: Test variable refresh rate on Linux
description: |-
  **Packager-specific information**

  This is NOT an official distribution of VRRTest, please file any issue
  regarding the usage of this snap to the snap's own issue tracker:

      Issues · 林博仁 Buo-ren, Lin / Unofficial snap packaging for VRRTest · GitLab
      https://gitlab.com/brlin/vrrtest-snap/-/issues

  Refer to the upstream project website for more info about this application:

      Nixola/VRRTest: A small utility I wrote to test variable refresh rate on
      Linux. Should work on all major OSes.
      https://github.com/Nixola/VRRTest

base: core22
assumes:
  - command-chain
adopt-info: vrrtest
grade: stable
confinement: strict
compression: lzo
icon: snap/gui/placeholder-icon.png
license: Zlib
contact: https://gitlab.com/brlin/vrrtest-snap/-/issues
issues: https://gitlab.com/brlin/vrrtest-snap/-/issues
source-code: https://gitlab.com/brlin/vrrtest-snap
website: https://gitlab.com/brlin/vrrtest-snap

# s390x does not have the love package at the moment
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: ppc64el

parts:
  vrrtest:
    source: https://github.com/Nixola/VRRTest.git
    plugin: dump
    organize:
      '*': VRRTest/
    build-packages:
      # selective-checkout dependencies
      - curl
      - jq
      - sed
      - git
    override-pull: |
      set -o nounset

      if ! craftctl default; then
          printf \
            'Error: Unable to run the default step handler.\n' \
            1>&2
          exit 2
      fi

      if ! "${CRAFT_PROJECT_DIR}/snap/local/scriptlets/selective-checkout" \
          --append-packaging-revision; then
          printf \
            'Error: Unable to run the selective-checkout program.\n' \
            1>&2
          exit 2
      fi

  vrrtest-runtime-deps:
    plugin: nil
    stage-packages:
      - love
      - libgl1
    prime:
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libicutest.so*
      - -usr/lib/*/libicutu.so*
      - -usr/lib/*/libpulse-simple.so*
      - -usr/lib/*/libtheora.so*
      - -usr/lib/*/libtheoraenc.so*

  desktop-glib-only:
    build-packages:
      - libglib2.0-dev
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    stage-packages:
      - libglib2.0-bin

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*

  maintainer-notice:
    source: snap/local/maintainer-notice
    plugin: dump
    organize:
      '*': maintainer-notice/

lint:
  ignore:
    - library:
        - usr/lib/*/libGL*.so*
        - usr/lib/*/libxcb-*.so.*
        - usr/lib/*/libxshmfence.so.*

apps:
  vrrtest:
    command: usr/bin/love-11.3 $SNAP/VRRTest
    command-chain:
      - bin/desktop-launch
      - bin/vrrtest-launch
    plugs:
      - desktop
      - opengl
      - wayland
      - x11
